train: /Users/jayashre/Developer/VSC/drone-vs-bird-challenge/training_dataset/train/ # Path to training images
val: /Users/jayashre/Developer/VSC/drone-vs-bird-challenge/training_dataset/val/    # Path to validation images
test: /Users/jayashre/Developer/VSC/drone-vs-bird-challenge/training_dataset/test/

nc: 1                           # Number of classes (1 for drone detection)
names: ['drone']                # Class name(s)
